service: image-uploader-bucket

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-1

custom:
  fileUploadBucketName: ${self:service}-bucket-${self:provider.stage}

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: image-uploader-bucket
        AccessControl: PublicRead
